
CREATE DATABASE CSIIDEMO ALIAS CSIIDEMO USING CODESET UTF-8 TERRITORY CN;

UNCATALOG DATABASE PEDEMO;

CATALOG DATABASE PEDEMO AS PEDEMO WITH 'PE Demo Banking';

CATALOG DATABASE PEDEMO AS PEDEMO WITH "PE Demo Banking";


